# Generated by Django 5.1.1 on 2024-10-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_producst'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producst',
            new_name='Product',
        ),
    ]
