# Generated by Django 5.1.1 on 2024-10-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_category_created_at_category_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-02-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart_item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-02-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-02-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
